-- Schema PostgreSQL esperado pelo backend SAP.
-- Execute no Supabase apenas se as tabelas ainda nao existirem.
-- Este arquivo nao contem comandos destrutivos.

create table if not exists unidades (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null unique,
    endereco varchar(255) not null,
    telefone varchar(255) not null,
    created_at timestamp(6) not null
);

create table if not exists usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    email varchar(255) not null unique,
    usuario varchar(255) unique,
    senha varchar(255) not null,
    tipo_usuario varchar(255) not null,
    ativo boolean not null,
    senha_temporaria boolean not null,
    unidade_id bigint references unidades(id),
    created_at timestamp(6) not null
);

create table if not exists cursos (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    tipo_aprendizagem varchar(255),
    descricao text,
    ativo boolean not null,
    unidade_id bigint not null references unidades(id),
    created_at timestamp(6) not null,
    constraint uk_cursos_nome_unidade unique (nome, unidade_id)
);

create table if not exists turmas (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    turno varchar(255) not null,
    ativo boolean not null,
    curso_id bigint not null references cursos(id),
    unidade_id bigint not null references unidades(id),
    instrutor_id bigint references usuarios(id),
    created_at timestamp(6) not null,
    constraint uk_turmas_nome_curso_unidade unique (nome, curso_id, unidade_id)
);

create table if not exists alunos (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    cpf varchar(255) not null unique,
    data_nascimento date not null,
    telefone varchar(255) not null,
    email varchar(255),
    responsavel varchar(255) not null,
    turno varchar(255) not null,
    observacoes text,
    ativo boolean not null,
    unidade_id bigint references unidades(id),
    curso_id bigint references cursos(id),
    turma_id bigint references turmas(id),
    created_at timestamp(6) not null
);

create table if not exists atendimentos (
    id bigint generated by default as identity primary key,
    titulo varchar(255) not null,
    descricao text not null,
    data_atendimento timestamp(6) not null,
    status varchar(255) not null,
    observacoes text,
    relatorio_consulta text,
    tipo_atendimento varchar(30),
    categoria_atendimento varchar(80),
    aluno_id bigint references alunos(id),
    psicologo_id bigint references usuarios(id),
    solicitante_id bigint references usuarios(id),
    created_at timestamp(6) not null
);

create table if not exists agenda_eventos (
    id bigint generated by default as identity primary key,
    titulo varchar(255) not null,
    descricao text,
    tipo varchar(255) not null,
    data_inicio timestamp(6) not null,
    data_fim timestamp(6),
    dia_inteiro boolean not null,
    cor varchar(255),
    psicologo_id bigint references usuarios(id),
    unidade_id bigint references unidades(id),
    created_at timestamp(6) not null,
    updated_at timestamp(6)
);

create table if not exists chat_mensagens (
    id bigint generated by default as identity primary key,
    remetente_id bigint not null references usuarios(id),
    destinatario_id bigint not null references usuarios(id),
    unidade_id bigint references unidades(id),
    texto text not null,
    lida boolean not null,
    created_at timestamp(6) not null
);

create index if not exists idx_chat_participantes
    on chat_mensagens (remetente_id, destinatario_id);
